# Generated by Django 5.0.6 on 2024-06-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('Coursecode', models.CharField(max_length=20)),
                ('CourseTitle', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'course_table',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_id', models.BigIntegerField()),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('password', models.CharField(default='klu@123', max_length=100)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('contact', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'faculty_table',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.BigIntegerField()),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('Program', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('password', models.CharField(default='klu@123', max_length=100)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('contact', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'student_table',
            },
        ),
    ]
