# Generated by Django 5.0.6 on 2024-06-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('CSE(Regular)', 'CSE(R)'), ('CSE(HONORS)', 'CSE(H)'), ('CS&IT', 'CSIT')], max_length=100),
        ),
    ]
