# Generated by Django 5.0.6 on 2024-06-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='academic_year',
            field=models.CharField(choices=[('2022-23', '2022-23'), ('2023-24', '2023-24')], max_length=100),
        ),
    ]
