# Generated by Django 5.0.6 on 2024-06-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_faculty_department_alter_faculty_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
