# Generated by Django 5.0.6 on 2024-06-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_faculty_faculty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Program',
            field=models.CharField(choices=[('B.TECH', 'B.TECH'), ('M.TECH', 'M.TECH')], default='B.TECH', max_length=100),
        ),
    ]
