# Generated by Django 5.0.6 on 2024-06-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_facultycoursemapping_component_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultycoursemapping',
            name='type',
        ),
        migrations.AddField(
            model_name='facultycoursemapping',
            name='faculty_type',
            field=models.CharField(choices=[('Main', 'MainFaculty'), ('Assist', 'Assistance')], default='Main', max_length=20),
            preserve_default=False,
        ),
    ]
